language: python

python:
    - "3.7"

before_install:
    - sudo apt-get update
    - sudo apt-get install python3

install:
    - python3 setup.py install 

script:
    - bash workflow_example/edges_of_customer.sh
